version: "3.7"
services:
  web:
    container_name: web
    image: nginx:alpine
    depends_on: 
      - app
    ports:
      - 8082:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1121
    expose:
      - 1121
    env_file:
      - .env-non-dev


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9998:8000
    depends_on:
      - db

  